---

- import_role:
    name: t18s.fr_firewall_config
  vars:
    firewall_config_name: 420ntpd
    firewall_config_ipv4_rules: "{{ openntpd_firewall_config_ipv4_rules }}"
    firewall_config_ipv6_rules: "{{ openntpd_firewall_config_ipv6_rules }}"
