---

- name: load os specific vars
  include_vars: "{{ ansible_facts['distribution'] }}.yml"
  tags: always

- import_tasks: pkg.yml
  when: ansible_facts['os_family'] != 'OpenBSD'

- import_tasks: config.yml

- import_tasks: service.yml

- meta: flush_handlers

- import_tasks: fw.yml

- import_tasks: remove_other_ntpd.yml
